[versions]
kmongo = "4.9.0"
kord-extensions = "1.5.6"
kordx-emoji = "0.5.0"
slf4j = "2.0.7"

[libraries]
kmongo-coroutine = { module = "org.litote.kmongo:kmongo-coroutine", version.ref = "kmongo" }
kordextensions-kordextensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kordextensions-unsafe = { module = "com.kotlindiscord.kord.extensions:unsafe", version.ref = "kord-extensions" }
kordx-emoji = { module = "dev.kord.x:emoji", version.ref = "kordx-emoji" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }